HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
    public Stylist()
    {
      this.Clients = new HashSet<Client>();
      this.Appointments = new HashSet<Appointment>();
    }

    public int StylistId { get; set; }
    public string Name { get; set; }
    public string Specialty { get; set; }
    public virtual ICollection<Client> Clients { get; set; }
    public virtual ICollection<Appointment> Appointments { get; set; }
  }
}

HairSalon/Controllers/AppointmentsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace HairSalon.Controllers
{
  public class AppointmentsController : Controller
  {
    private readonly HairSalonContext _db;

    public AppointmentsController(HairSalonContext db)
    {
      _db = db;
    } 

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Appointment appointment)
    {
      try
      {
        if (String.IsNullOrWhiteSpace(appointment.Date) || String.IsNullOrWhiteSpace(appointment.Notes))
        {
          throw new System.InvalidOperationException("Invalid input");
        }
        else if (Validation.CheckDateFormat(appointment.Date) == 1)
        {
          List<Appointment> existingAppts = _db.Appointments.Where(appt => appt.StylistId == appointment.StylistId).ToList();
          for (int i=0; i< existingAppts.Count; i++)
          {
            if (existingAppts[i].Date == appointment.Date && existingAppts[i].Time == appointment.Time)
            {
              throw new System.InvalidOperationException("Selected date and/or time unavailable. Please try again.");
            }
          }
          _db.Appointments.Add(appointment);
          _db.SaveChanges();
          return RedirectToAction("Index", "Stylists");
        }
        else
        {
          throw new System.InvalidOperationException("Invalid date. Please try again.");
        }
      }
      catch (Exception ex)
      {
        return View("Error", ex.Message);
      }
    }
  }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System;

namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db =db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      model.Sort((x, y) => string.Compare(x.Name, y.Name));
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      try
      {
        if (String.IsNullOrWhiteSpace(stylist.Name) || String.IsNullOrWhiteSpace(stylist.Specialty))
        {
          throw new System.InvalidOperationException("Invalid input");
        }
        else
        {
          _db.Stylists.Add(stylist);
          _db.SaveChanges();
          return RedirectToAction("Index");
        }
      }
      catch (Exception ex)
      {
        return View("Error", ex.Message);
      }
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      thisStylist.Clients = _db.Clients.Where(client => client.StylistId == id).ToList();
      thisStylist.Appointments = _db.Appointments.Where(appointment => appointment.Stylist.Name == thisStylist.Name).ToList();
      return View(thisStylist);
    }

    public ActionResult Edit(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist stylist)
    {
      try
      {
        if (String.IsNullOrWhiteSpace(stylist.Name) || String.IsNullOrWhiteSpace(stylist.Specialty))
        {
          throw new System.InvalidOperationException("Invalid input");
        }
        else
        {
          _db.Entry(stylist).State = EntityState.Modified;
          _db.SaveChanges();
          return RedirectToAction("Index");
        }
      }
      catch (Exception ex)
      {
        return View("Error", ex.Message);
      }
    }

    public ActionResult Delete(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      thisStylist.Clients = _db.Clients.Where(client => client.StylistId == id).ToList();
      thisStylist.Appointments = _db.Appointments.Where(appt => appt.StylistId == id).ToList();
      foreach(Client client in thisStylist.Clients)
      {
        _db.Clients.Remove(client);
      }
      foreach(Appointment appointment in thisStylist.Appointments)
      {
        _db.Appointments.Remove(appointment);
      }
      _db.Stylists.Remove(thisStylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h1>ADD NEW STYLIST</h1>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Specialty)
  @Html.TextBoxFor(model => model.Specialty)
  <br>
  <input type="submit" class="btn-block" value="ADD STYLIST" />
}
@Html.ActionLink("RETURN TO ALL STYLISTS", "Index", "Stylists",  null, new { @class = "btn-block" })

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h1>DELETE THIS STYLIST?</h1>
<h4>@Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  <input type="submit" value="CONFIRM DELETION" class="btn-block"/>
}

@Html.ActionLink("SHOW ALL STYLISTS", "Index", "Stylists", null, new { @class = "btn-block" })

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model HairSalon.Models.Stylist;

<h1>@Html.DisplayFor(model => model.Name)</h1>
<h4>@Html.DisplayFor(model => model.Specialty) specialist</h4>
<hr />
@if (@Model.Clients.Count == 0)
{
  <h4>no clients found</h4>
} else
{
  <h4>CURRENT CLIENTS</h4>
  <ul>
    @foreach (Client client in @Model.Clients)
    {
      <li><a href="/Clients/Details/@client.ClientId">@client.Name</a></li>
    }
  </ul>
}

@if (@Model.Appointments.Count > 0)
{
  <h4>UPCOMING APPOINTMENTS</h4>
  <div class="appts">
    @foreach (Appointment appointment in @Model.Appointments)
    {
      <div class="appointment">
        <p>DATE: @appointment.Date</p>
        <p>TIME: @appointment.Time</p>
        <p>NOTES: @appointment.Notes</p>
      </div>
    }
  </div>
}

<div class="stylist-buttons">
  <a href="/Clients/Create" class="btn">ADD CLIENT</a>
  @Html.ActionLink("SCHEDULE APPOINTMENT", "Create", "Appointments", null, new { @class = "btn" })
  @Html.ActionLink("EDIT DETAILS", "Edit", "Stylists", new { id = Model.StylistId }, new { @class = "btn" })
  @Html.ActionLink("DELETE STYLIST", "Delete", "Stylists", new { id = Model.StylistId }, new { @class = "btn" })
</div>
@Html.ActionLink("VIEW ALL STYLISTS", "Index", "Stylists", null, new { @class = "btn-block" })

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h1>EDIT DETAILS FOR: @Html.DisplayFor(model => model.Name)</h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Specialty)
  @Html.EditorFor(model => model.Specialty)
  <br>
  <input type="submit" class="btn-block" value="SAVE" />
}

@Html.ActionLink("SHOW ALL STYLISTS", "Index", "Stylists", null, new { @class = "btn-block" })

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Stylist>

<h1>STYLISTS</h1>

@if(@Model.Count == 0)
{
  <h4>Eau Claire's Salon is seeking talented stylists!</h4>
}

@foreach (Stylist stylist in Model)
{
  <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
}

<div class="stylist-index-buttons">
  @Html.ActionLink("ADD NEW STYLIST", "Create", "Stylists", null, new { @class = "btn" })
  @Html.ActionLink("SCHEDULE APPOINTMENT", "Create", "Appointments", null, new { @class = "btn" })
</div>