HairSalon/Models/Client.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public string Name { get; set; }
    public string Notes { get; set; }
    public int StylistId { get; set; }
    public virtual Stylist Stylist { get; set; }
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    } 

    public ActionResult Index()
    {
      List<Client> model = _db.Clients.ToList();
      model.Sort((x, y) => string.Compare(x.Name, y.Name));
      return View(model);
    }

    public ActionResult Create()
    {
      try
      {
        List<Stylist> stylists = _db.Stylists.ToList();
        if (stylists.Count >= 1)
        {
          ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
          return View();
        }
        else
        {
          throw new System.InvalidOperationException("There are currently no stylists available for new clients.");
        }
      }
      catch (Exception ex)
      {
        return View("Error", ex.Message);
      }
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      try
      {
        if (String.IsNullOrWhiteSpace(client.Name) || String.IsNullOrWhiteSpace(client.Notes))
        {
          throw new System.InvalidOperationException("Invalid input");
        }
        else
        {
          _db.Clients.Add(client);
          _db.SaveChanges();
          return RedirectToAction("Index");
        }
      }
      catch (Exception ex)
      {
        return View("Error", ex.Message);
      }
    }

    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
      ViewBag.Stylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == thisClient.StylistId);
      return View(thisClient);
    }

    public ActionResult Delete(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
      return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Client thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
      _db.Clients.Remove(thisClient);
      _db.SaveChanges();
      return RedirectToAction("Index", "Stylists");
    }
  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h1>ADD NEW CLIENT</h1>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Notes)
  @Html.TextBoxFor(model => model.Notes)
  <br>
  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId")
  <input type="submit" value="ADD CLIENT" class="btn-block" />
}

@Html.ActionLink("VIEW ALL CLIENTS", "Index", "Clients", null, new { @class = "btn-block" })

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h1>DELETE THIS CLIENT?</h1>
<h4>@Html.DisplayFor(model => model.Name)</h4>
@using (Html.BeginForm())
{
  <input type="submit" class="btn-block" value="CONFIRM DELETION" />
}

@Html.ActionLink("SHOW ALL CLIENTS", "Index", "Clients", null, new { @class = "btn-block" })

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model HairSalon.Models.Client

<h1>@Html.DisplayFor(model => model.Name)</h1>
<hr />
<h4>STYLIST: @ViewBag.Stylist.Name</h4>
<h4>NOTE: @Html.DisplayFor(model => model.Notes)</h4>

<div class="client-buttons">
  @Html.ActionLink("DELETE CLIENT", "Delete", "Clients", new { id = Model.ClientId }, new { @class = "btn" })
  @Html.ActionLink("SHOW ALL CLIENTS", "Index", "Clients", null, new { @class = "btn" })
</div>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>

@if (@Model.Count == 0)
{
  <h1>no clients found</h1>
} else
{
  <h1>CLIENTELE</h1>
  <hr />
  <ul>
    @foreach (Client client in Model)
    {
    <li>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId })</li>
    }
  </ul>
}

@Html.ActionLink("SHOW ALL STYLISTS", "Index", "Stylists", null, new { @class = "btn-block" })